pt6-apparatusL3-project/apparatusl3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
          # Adds allauth URLs
    path('accounts/', include('allauth.urls')),
    path('', include('l3users.urls')),
    path('meetings/', include('l3meetings.urls')),
    path('invites/', include('invites.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

pt6-apparatusL3-project/invites/urls.py
from django.urls import path
from .views import *

app_name = 'invites'

urlpatterns = [
    path('<int:pk>/edit-invite', UpdateInvite.as_view(), name='update_invite'),
]

pt6-apparatusL3-project/invites/models.py
from django.db import models
from l3meetings.models import Meeting
from ckeditor.fields import RichTextField

# Create your models here.
class MeetingInvites(models.Model):
    meeting = models.OneToOneField(Meeting, on_delete=models.CASCADE)
    # invite_details = models.TextField(max_length=300, null=True)
    invite_details = RichTextField()
    invitees = models.TextField(null=False, default='')

    def __str__(self):
        return f"Schedule for Meeting: {self.meeting.title}"

pt6-apparatusL3-project/l3meetings/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField


class DeliveryUnit(models.Model):
    title = models.CharField(max_length=250, unique=True)
    description = models.TextField(max_length=250)

    def __str__(self):
        return self.title


class Meeting(models.Model):

    title = models.CharField(max_length=250, unique=True)
    description = models.TextField(max_length=250)
    meeting_date = models.DateTimeField()
    delivery_unit = models.ForeignKey(DeliveryUnit, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_superuser': False})
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class MeetingNotes(models.Model):

    note_description = RichTextField()
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    class Meta:
        verbose_name = "Meeting Notes"

    def __str__(self):
        return self.note_description



class Agenda(models.Model):

    status_choices = (
        ('open', 'Open'),
        ('close', 'Close'),
    )

    title = models.CharField(max_length=70)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    is_default = models.BooleanField(default=False)
    status = models.CharField(
        max_length=10,
        choices=status_choices,
        default='open'
    )

    class Meta:
        verbose_name = "Agenda"
        verbose_name_plural = "Agendas"

    def __str__(self):
        return self.title

    @property
    def created_by_first_name(self):
        return self.created_by.first_name if self.created_by else ''


class ActionItem(models.Model):

    status_choices = (
        ('open', 'Open'),
        ('close', 'Close'),
        ('inprogress', 'In-Progress'),
    )

    assignedto = models.ForeignKey(
        User, on_delete=models.CASCADE)
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    start_date = models.DateTimeField()
    target_end_date = models.DateTimeField()
    actual_end_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE, related_name='author')
    agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE)

    status = models.CharField(
        max_length=10,
        choices=status_choices,
        default='open'
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.author is None and 'current_user' in kwargs:
            self.author = kwargs.pop('current_user')
        super().save(*args, **kwargs)


class DeliveryUnitDefaultAgenda(models.Model):
    delivery_unit = models.ForeignKey(DeliveryUnit, on_delete=models.CASCADE)
    agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Delivery Unit Default Agenda"

    def __str__(self):
        return self.delivery_unit.title+' => '+self.agenda.title


class MeetingAgenda(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Meeting Agenda"

    def __str__(self):
        return self.meeting.title+' => '+self.agenda.title

class Response(models.Model):
    action_item = models.ForeignKey(ActionItem, on_delete=models.CASCADE)
    response_date = models.DateTimeField(default=timezone.now)
    responded_by = models.CharField(max_length=100)
    response_text = models.TextField()

    def __str__(self):
        return f"Response by {self.responded_by} on {self.response_date}"
    

class MeetingAttendance(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_present = models.BooleanField(default=False)

pt6-apparatusL3-project/invites/forms.py
from django import forms
from .models import MeetingInvites
from l3meetings.models import Meeting
from django.contrib.auth.models import User
from django.db.models.functions import Lower
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from ckeditor.widgets import CKEditorWidget

class MeetingsScheduleForm(forms.ModelForm):
    meeting = forms.ModelChoiceField(queryset=Meeting.objects.all(), required=True)
    meeting_date = forms.DateField(required=True)
    invite_details = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = MeetingInvites
        fields = [
            'meeting',
            'invite_details',
            'meeting_date',
            'invitees',
        ]
    
    def clean(self):
        cleaned_data = super().clean()
        meeting = cleaned_data.get('meeting')
        invitees = cleaned_data.get('invitees')
        edit_mode = self.instance.pk is not None

        if not edit_mode:
            if meeting and MeetingInvites.objects.filter(meeting=meeting).exists():
                self.add_error('meeting', 'This meeting is already scheduled.')
        
        if invitees:
            invitees_list = invitees.split(',')
            invalid_emails = []
            for invitee in invitees_list:
                invitee = invitee.strip()
                try:
                    validate_email(invitee)
                except ValidationError:
                    invalid_emails.append(invitee)
            
            if invalid_emails:
                self.add_error('invitees', f'These emails are invalid: {", ".join(invalid_emails)}')
        
        return cleaned_data

    def __init__(self, *args, pk=None, **kwargs):
        super(MeetingsScheduleForm, self).__init__(*args, **kwargs)
        meeting_id = pk

        if self.instance.pk:
            self.fields['meeting'].initial = self.instance.meeting
            self.fields['meeting'].queryset = Meeting.objects.filter(pk=self.instance.meeting.id)
            self.fields['meeting'].widget.attrs.update({'readonly': 'true'})
            self.fields['meeting_date'].initial = self.instance.meeting.meeting_date
        else:
            if meeting_id:
                meeting = Meeting.objects.get(id=meeting_id)
                self.fields['meeting'].initial = meeting
                self.fields['meeting'].queryset = Meeting.objects.filter(pk=meeting_id)
                self.fields['meeting'].widget.attrs.update({'readonly': 'true'})
                self.fields['meeting_date'].initial = meeting.meeting_date
            else:
                self.fields['meeting'].queryset = Meeting.objects.exclude(meetingschedule__isnull=False)
        
        for field_name, field in self.fields.items():
            if field_name == 'meeting_date':
                field.widget.attrs.update({'class': 'form-control datepicker'})
            else:
                field.widget.attrs.update({'class': 'form-control'})
    
    
    def save(self, commit=True):
        instance = super().save(commit=True)
        if instance.meeting:
            instance.meeting.meeting_date = self.cleaned_data['meeting_date']
            if commit:
                instance.meeting.save()
        return instance

pt6-apparatusL3-project/invites/views.py
from django.http import HttpResponseRedirect, request
from django.views.generic import TemplateView, FormView, UpdateView, View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from apparatusl3.decorators import has_permissions
from .models import Meeting, MeetingInvites
from .forms import MeetingsScheduleForm
from l3meetings.models import MeetingAgenda
    
    
@method_decorator(has_permissions(['invites.change_meetinginvites']), name='dispatch')
class UpdateInvite(LoginRequiredMixin, UpdateView):
    model = MeetingInvites
    form_class = MeetingsScheduleForm
    template_name = 'create.html'
    success_url = reverse_lazy('meetings_list')
    login_url = "/login/"
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return kwargs

    def get_object(self):
        meeting_id = self.kwargs.get('pk')
        invite = get_object_or_404(MeetingInvites, meeting__id=meeting_id)
        return invite
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Update Meeting Invite'
        return context
    
    def form_valid(self, form):
        try:
            form.save()
            messages.success(self.request, 'Meeting invite updated successfully.')
        except Exception as e:
            messages.error(self.request, 'There was an error updating the invite.')
            return self.form_invalid(form)
        return super().form_valid(form)


@method_decorator(has_permissions(['invites.delete_meetinginvites']), name='dispatch')
class DeleteSchedule(LoginRequiredMixin, View):
    success_url = reverse_lazy('invites:invite_list')

    def post(self, request, *args, **kwargs):
        obj = get_object_or_404(MeetingInvites, pk=kwargs['pk'])
        obj.delete()
        messages.success(request, 'The invite was deleted successfully.')
        return HttpResponseRedirect(self.success_url)
    

pt6-apparatusL3-project/invites/templates/create.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

<div class="col-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div class="d-flex align-items-center justify-content-between">
        <h4 class="card-title">Schedule A Meeting</h4>
        <a href="{% url 'meetings_list' %}" class="btn btn-primary history_btn">
            <i class="fa fa-chevron-circle-left"></i>
            Go Back
        </a>
      </div>
      <hr>
      <form method="post" action="">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6">
              <div class="form-group">
                  <div class="form-floating">
                    {{ form.meeting }}
                    <label for="id_meeting">Select A Meeting</label>
                    {{ form.meeting.errors }}
                  </div>
              </div>
          </div>
          <div class="col-md-6">
              <div class="form-group">
                  <div class="form-floating">
                    <lable>Did not find your meeting?</lable>
                    <a href="{% url 'create_meeting' %}" class="btn btn-primary">Add Meeting</a>
                  </div>
              </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label for="id_invite_details">Invite details</label>
              <div class="form-floating">
                {{ form.invite_details }}
                {{ form.invite_details.errors }}
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <div class="form-floating datepicker_wrapper">
                  {{ form.meeting_date }}
                  <label class="required" for="id_start_date">Meeting Date</label>
                  <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                      </span>
                  </div>
                  {{ form.meeting_date.errors }}
              </div>
          </div>
        </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <div class="form-floating">
                {{ form.invitees }}
                <label for="id_invitees">Invitees</label>
                {{ form.invitees.errors }}
              </div>
            </div>
          </div>
        </div>
        <div class="text-right">
          <button type="submit" class="btn btn-primary mb-2">
            Schedule Meeting
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}