pt6-apparatusL3-project/apparatusl3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
          # Adds allauth URLs
    path('accounts/', include('allauth.urls')),
    path('', include('l3users.urls')),
    path('meetings/', include('l3meetings.urls')),
    path('invites/', include('invites.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

pt6-apparatusL3-project/invites/urls.py
from django.urls import path
from .views import *

app_name = 'invites'

urlpatterns = [
    path('<int:pk>/edit-invite', UpdateInvite.as_view(), name='update_invite'),
]

pt6-apparatusL3-project/l3meetings/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', MeetingIndexView.as_view(), name='meetings_list'),
    path('<slug:slug>', MeetingDetailView.as_view(), name='meeting_detail'),
    path('create/', CreateMeeting.as_view(), name='create_meeting'),
    path('<int:pk>/edit', UpdateMeeting.as_view(), name='update_meeting'),
    path('<int:pk>/delete', DeleteMeeting.as_view(), name='delete_meeting'),
    path('<int:pk>/action-items', MeetingActionItems.as_view(), name='meeting_action_items'),
    path('agenda/<int:pk>/update/', UpdateAgenda.as_view(), name="update_agenda"),
    path('agendas', AgendaIndexView.as_view(), name='agendas_list'),
    path('<slug:slug>/agenda/create/', CreateAgendaView.as_view(), name='create_agenda'),
    path('action-items/', ActionItemIndexView.as_view(), name='action_item_list'),
    path('my-action-items/', CurrentUserActionItems.as_view(), name='current_user_action_item_list'),
    path('action-items/create/', CreateActionItem.as_view(), name='create_actionitem'),
    path('action-items/<int:pk>/edit', UpdateActionItem.as_view(), name='update_actionitem'),
    path('action-items/<int:pk>/delete', DeleteActionItem.as_view(), name='delete_actionitem'),
    path('action-item/responses/<int:pk>/add', AddResponseView.as_view(), name='add_response'),
    path('action-item/responses/<int:pk>/view/', ViewResponses.as_view(), name='view_responses'),
    path('meeting-notes/create/', CreateMeetingNotes.as_view(), name='create_meeting_notes'),
    path('meeting-notes/<int:pk>/edit/', UpdateMeetingNotes.as_view(), name='edit_meeting_notes'),
    path('schedule/', MeetingSchedulerView.as_view(), name='schedule_meeting'),
]

pt6-apparatusL3-project/l3meetings/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField


class DeliveryUnit(models.Model):
    title = models.CharField(max_length=250, unique=True)
    description = models.TextField(max_length=250)

    def __str__(self):
        return self.title


class Meeting(models.Model):

    title = models.CharField(max_length=250, unique=True)
    description = models.TextField(max_length=250)
    meeting_date = models.DateTimeField()
    delivery_unit = models.ForeignKey(DeliveryUnit, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_superuser': False})
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class MeetingNotes(models.Model):

    note_description = RichTextField()
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    class Meta:
        verbose_name = "Meeting Notes"

    def __str__(self):
        return self.note_description



class Agenda(models.Model):

    status_choices = (
        ('open', 'Open'),
        ('close', 'Close'),
    )

    title = models.CharField(max_length=70)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    is_default = models.BooleanField(default=False)
    status = models.CharField(
        max_length=10,
        choices=status_choices,
        default='open'
    )

    class Meta:
        verbose_name = "Agenda"
        verbose_name_plural = "Agendas"

    def __str__(self):
        return self.title

    @property
    def created_by_first_name(self):
        return self.created_by.first_name if self.created_by else ''


class ActionItem(models.Model):

    status_choices = (
        ('open', 'Open'),
        ('close', 'Close'),
        ('inprogress', 'In-Progress'),
    )

    assignedto = models.ForeignKey(
        User, on_delete=models.CASCADE)
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    start_date = models.DateTimeField()
    target_end_date = models.DateTimeField()
    actual_end_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE, related_name='author')
    agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE)

    status = models.CharField(
        max_length=10,
        choices=status_choices,
        default='open'
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.author is None and 'current_user' in kwargs:
            self.author = kwargs.pop('current_user')
        super().save(*args, **kwargs)


class DeliveryUnitDefaultAgenda(models.Model):
    delivery_unit = models.ForeignKey(DeliveryUnit, on_delete=models.CASCADE)
    agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Delivery Unit Default Agenda"

    def __str__(self):
        return self.delivery_unit.title+' => '+self.agenda.title


class MeetingAgenda(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Meeting Agenda"

    def __str__(self):
        return self.meeting.title+' => '+self.agenda.title

class Response(models.Model):
    action_item = models.ForeignKey(ActionItem, on_delete=models.CASCADE)
    response_date = models.DateTimeField(default=timezone.now)
    responded_by = models.CharField(max_length=100)
    response_text = models.TextField()

    def __str__(self):
        return f"Response by {self.responded_by} on {self.response_date}"
    

class MeetingAttendance(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_present = models.BooleanField(default=False)

pt6-apparatusL3-project/l3meetings/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import TemplateView, FormView, UpdateView, View, ListView
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render, redirect
from django.core.exceptions import PermissionDenied,ObjectDoesNotExist
from .utils import UserUtils
from apparatusl3.decorators import has_permissions, has_role
from .models import *
from .forms import *
from django.db.models.signals import post_save
from .signals import meeting_saved
from django.contrib.auth.models import Group
from django.db import transaction
from django.utils import timezone
from datetime import timedelta
from pytz import timezone as tz
from django.db.models import Count, F
from sitesettings.email_notifications import *
from sitesettings.context_processors import get_holiday_dates
from sitesettings.context_processors import load_site_settings

local_tz = tz('Asia/Kolkata')
@method_decorator(has_permissions(['l3meetings.view_meeting']), name='dispatch')
class MeetingIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'meetings/index.html'
    login_url = "/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Actions'
        context['meetings'] = Meeting.objects.all().order_by('-id')
        return context

@method_decorator(has_permissions(['l3meetings.view_meeting']), name='dispatch')
class MeetingDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'meetings/single.html'
    login_url = "/login/"
    
    def get(self, request, *args, **kwargs):
        request.session['origin_url'] = request.path
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(load_site_settings(self.request))
        meeting = Meeting.objects.get(slug=self.kwargs['slug'])
        context['page_title'] = 'Actions'
        context['meeting'] = meeting
        context['agendas'] = Agenda.objects.filter(meetingagenda__meeting=meeting).order_by("-is_default")
        context['action_items'] = ActionItem.objects.filter(meeting=meeting).order_by('-id')
        action_items = ActionItem.objects.filter(meeting=meeting).order_by('-id')
        unique_actions = {}

        for item in action_items:
            if item.title not in unique_actions:
                user = User.objects.get(id=item.assignedto_id)
                unique_actions[item.title] = {
                    'id': item.id,
                    'title': item.title,
                    'assignedto': {
                        'first_name': user.first_name,
                        'last_name': user.last_name,
                    },
                    'author_id': item.author_id,
                    'agenda_id': item.agenda_id,
                    'count': 1,
                }
            else:
                unique_actions[item.title]['count'] += 1

        context['action_items'] =  list(unique_actions.values())
        context['action_item_form'] = ActionItemForm(initial={'assignedto': self.request.user})
        meeting_notes, created = MeetingNotes.objects.get_or_create(meeting=meeting)
        context['meeting_notes_form'] = MeetingNotesForm(instance=meeting_notes)
        context['meeting_attendance_form'] = MeetingAttendanceForm(meeting=meeting)
        return context

    def get_success_url(self):
        origin_url = self.request.session.get('origin_url')
        del self.request.session['origin_url']
        return origin_url

    def post(self, request, *args, **kwargs):
        is_email_sending_allowed = self.get_context_data()['allow_email_send']
        
        match self.request.POST.get('form_name'):
            case 'add_agenda':
                try:
                    title = self.request.POST.get('agenda_title')
                    status = self.request.POST.get('status')
                    meeting_id = self.request.POST.get('meeting_id')
                    meeting = Meeting.objects.get(id=meeting_id)

                    agenda = Agenda(title=title, status=status,
                                    created_by=request.user)

                    agenda.save()
                    MeetingAgenda.objects.create(meeting=meeting, agenda=agenda)
                    # meeting_saved.send(sender=Meeting, instance=self.object, created=True, user=self.request.user)
                    messages.success(self.request, 'Agenda Created successfully.')
                except Exception as e:
                    print(e)
                    messages.error(self.request, 'There was an error creating the agenda.')
                return redirect(self.get_success_url())  
            
            case 'add_action_item':
                try:
                    assignedto = self.request.POST.get('assignedto')
                    title = self.request.POST.get('title')
                    meeting_id = self.request.POST.get('meeting_id')
                    agenda_id = self.request.POST.get('agenda_id')
                    meeting = Meeting.objects.get(id=meeting_id)
                    agenda = Agenda.objects.get(id=agenda_id)
                    user = User.objects.get(id=assignedto)
                    start_date = datetime.date.today()
                    target_end_date = start_date + datetime.timedelta(days=7)
                    superUsr = User.objects.filter(pk=assignedto, is_superuser=True).values()
                    
                    all_users =  User.objects.filter(is_superuser=False)

                    if superUsr:
                        action_items_for_all = [
                            ActionItem(assignedto=usereach, meeting=meeting,title=title,start_date=start_date,target_end_date=target_end_date,agenda=agenda,author=self.request.user)
                            for usereach in all_users
                        ]
                        ActionItem.objects.bulk_create(action_items_for_all)
                    else:
                        actionitem = ActionItem(assignedto=user,meeting=meeting,title=title,start_date=start_date,target_end_date=target_end_date,agenda=agenda,author=self.request.user)
                        actionitem.save()
                        if actionitem.assignedto:
                            if is_email_sending_allowed == '1':
                                send_action_item_notification_email(actionitem,'create')
                
                    messages.success(self.request, 'Action Item Created successfully.')

                except Exception as e:
                    print(e)
                    messages.error(self.request, 'There was an error creating the action item.')
                return redirect(self.get_success_url())
            
            case 'add_meeting_note':
                self.handle_add_meeting_note(request)
            
            case 'add_meeting_attendance':
                self.handle_add_meeting_attendance(request)
                
        return redirect(self.get_success_url())
          

    def handle_add_meeting_note(self, request):
        meeting = get_object_or_404(Meeting, slug=self.kwargs['slug'])
        meeting_notes, created = MeetingNotes.objects.get_or_create(meeting=meeting)
        meeting_notes_form = MeetingNotesForm(request.POST, instance=meeting_notes)
        if meeting_notes_form.is_valid():
            meeting_notes = meeting_notes_form.save(commit=False)
            meeting_notes.meeting = meeting
            meeting_notes.save()
            messages.success(request, 'Meeting Note Updated successfully.')
        else:
            messages.error(request, 'There was an error adding the Meeting Note.')
            
    def handle_add_meeting_attendance(self, request):
        meeting = get_object_or_404(Meeting, slug=self.kwargs['slug'])
        absent_users = self.request.POST.get('absent_users', '').split(',')
        present_users = self.request.POST.get('present_users', '').split(',')
        
        absent_users = [user_id.strip() for user_id in absent_users if user_id.strip()]
        present_users = [user_id.strip() for user_id in present_users if user_id.strip()]

        for user_id in absent_users:
            try:
                user = User.objects.get(id=user_id)
                MeetingAttendance.objects.update_or_create(
                    meeting=meeting,
                    user=user,
                    defaults={'is_present': False}
                )
            except User.DoesNotExist:
                print(f'User with ID {user_id} does not exist.')

        for user_id in present_users:
            try:
                user = User.objects.get(id=user_id)
                MeetingAttendance.objects.update_or_create(
                    meeting=meeting,
                    user=user,
                    defaults={'is_present': True}
                )
            except User.DoesNotExist:
                print(f'User with ID {user_id} does not exist.')
        messages.success(request, 'Meeting attendance updated successfully.')

@method_decorator(has_permissions(['l3meetings.change_agenda']), name='dispatch')
class UpdateAgenda(LoginRequiredMixin, UpdateView):
    def post(self, request, *args, **kwargs):
        try:
            title = request.POST.get('agenda_title')
            agenda_id = request.POST.get('agenda_id')
            status = request.POST.get('status')

            if not title or not agenda_id or not status:
                return JsonResponse({'success': False, 'message': 'Missing required fields'}, status=400)

            try:
                agenda = Agenda.objects.get(id=agenda_id)
            except ObjectDoesNotExist:

pt6-apparatusL3-project/l3meetings/templates/meetings/create.html
{% extends 'base.html' %} {% block content %}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between">
                <h4 class="card-title">Create Meeting</h4>
                <a href="javascript:history.back();" class="btn btn-primary history_btn">
                    <i class="fa fa-chevron-circle-left"></i>
                    Go Back
                </a>
            </div>
            <input type="hidden" value="{{ holiday_list }}" name="holiday_list" id="holiday_list"/>
            <hr>
            <form method="post" action="" class="meeting_form">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.title }}
                                <label class="required" for="id_topic">Meeting Title</label>
                                {{ form.title.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating datepicker_wrapper ">
                                {{ form.meeting_date }}
                                <label class="required" for="id_meeting_date">Meeting Date</label>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-calendar" aria-hidden="true"></i>
                                    </span>
                                </div>
                                {% if form.meeting_date.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ form.meeting_date.errors }}
                                </div>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.delivery_unit }}
                                <label class="required" for="id_items">Delivery Unit</label>
                                {{ form.delivery_unit.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.assigned_to }}
                                <label class="required" for="id_items">Meeting Coordinator </label>
                                {{ form.assigned_to.errors }}
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.description }}
                                <label class="required" for="id_items">Description</label>
                                {{ form.description.errors }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary mb-2">
                        Add Meeting
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

pt6-apparatusL3-project/l3meetings/templates/meetings/edit.html
{% extends 'base.html' %} {% block content %}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between">
                <h4 class="card-title">Update Meeting</h4>
                <a href="javascript:history.back();" class="btn btn-primary history_btn">
                    <i class="fa fa-chevron-circle-left"></i>
                    Go Back
                </a>
            </div>
            <input type="hidden" value="{{ holiday_list }}" name="holiday_list" id="holiday_list"/>
            <hr>
            <form method="post" action="" class="meeting_form">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.title }}
                                <label class="required" for="id_topic">Meeting Title</label>
                                {{ form.title.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating datepicker_wrapper">
                                {{ form.meeting_date }}
                                <label class="required" for="id_start_date">Meeting Date</label>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                      <i class="fa fa-calendar" aria-hidden="true"></i>
                                    </span>
                                </div>
                                {{ form.meeting_date.errors }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.delivery_unit }}
                                <label class="required" for="id_items">Delivery Unit</label>
                                {{ form.delivery_unit.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.assigned_to }}
                                <label class="required" for="id_items">Meeting Coordinator </label>
                                {{ form.assigned_to.errors }}
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-floating">
                                {{ form.description }}
                                <label class="required" for="id_items">Description</label>
                                {{ form.description.errors }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary mb-2">
                        Update Meeting
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

pt6-apparatusL3-project/l3meetings/templates/meetings/index.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% load custom_filters %}

<div class="card">
    <div class="card-body">
        <div class="d-flex align-items-center justify-content-between">
            <h4 class="card-title">Meetings</h4>
            <div>
                <a href="{% url 'create_meeting' %}" class="btn btn-primary">Add Meeting</a>
                <a href="#" class="btn btn-primary ml-2" data-toggle="modal" data-target="#confirmModal">Schedule Next
                    Meeting</a>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <table id="meeting-listing" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>S.no</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Meeting Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for meeting in meetings %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'meeting_detail' meeting.slug %}">{{ meeting.title }}</a></td>
                            <td>{{ meeting.description }}</td>
                            <td>{{ meeting.meeting_date }}</td>
                            <td>
                                <a title="Edit Meeting" href="{% url 'update_meeting' meeting.id %}">
                                    <i class="fa fa-pencil-square"></i>
                                </a>
                                <a title="Edit Invite" href="{% url 'invites:update_invite' pk=meeting.id %}">
                                    <i class="fa fa-calendar"></i>
                                </a>
                                <a title="Delete Meeting" class="delete_meeting"
                                    data-href="{% url 'delete_meeting' meeting.id %}">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Confirm Schedule Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalLabel">Schedule Next Meeting</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you really want to schedule the next meeting?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" id="confirmYesButton">Yes</button>
            </div>
        </div>
    </div>
</div>

<!-- Schedule Modal -->
<div class="modal fade" id="scheduleModal" tabindex="-1" role="dialog" aria-labelledby="scheduleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="scheduleModalLabel">Select New Moderator</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'schedule_meeting' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.user.label_tag }}
                        {{ form.user }}
                    </div>
                    <button type="submit" class="btn btn-primary">Schedule Meeting</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% include 'partials/popups/delete.html' %}

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Handle Yes button click in the first modal
    document.getElementById('confirmYesButton').addEventListener('click', function() {
        // Redirect to /schedule/ URL
        window.location.href = "{% url 'schedule_meeting' %}";
    });

    // Check if URL is /schedule/ and if so, show the schedule modal
    console.log('----lll',window.location.pathname)
    if (window.location.pathname === '/meetings/schedule/') {
        setTimeout(function() {
            $('#scheduleModal').modal('show');
        }, 500); // Adjust delay as needed
    }
});
</script>

{% endblock %}